// This file was generated by counterfeiter
package apifakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/diego-enabler/api"
)

type FakeFilter struct {
	ToFilterQueryParamStub        func() string
	toFilterQueryParamMutex       sync.RWMutex
	toFilterQueryParamArgsForCall []struct{}
	toFilterQueryParamReturns     struct {
		result1 string
	}
}

func (fake *FakeFilter) ToFilterQueryParam() string {
	fake.toFilterQueryParamMutex.Lock()
	fake.toFilterQueryParamArgsForCall = append(fake.toFilterQueryParamArgsForCall, struct{}{})
	fake.toFilterQueryParamMutex.Unlock()
	if fake.ToFilterQueryParamStub != nil {
		return fake.ToFilterQueryParamStub()
	} else {
		return fake.toFilterQueryParamReturns.result1
	}
}

func (fake *FakeFilter) ToFilterQueryParamCallCount() int {
	fake.toFilterQueryParamMutex.RLock()
	defer fake.toFilterQueryParamMutex.RUnlock()
	return len(fake.toFilterQueryParamArgsForCall)
}

func (fake *FakeFilter) ToFilterQueryParamReturns(result1 string) {
	fake.ToFilterQueryParamStub = nil
	fake.toFilterQueryParamReturns = struct {
		result1 string
	}{result1}
}

var _ api.Filter = new(FakeFilter)
