resources:
- name: diego-enabler
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/diego-enabler
    private_key: {{diego_enabler_github_private_key}}
    branch: master

- name: diego-enabler-draft-release
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: Diego-Enabler
    access_token: {{cli-github-diego-enabler-release-token}}
    drafts: true

jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: diego-enabler
      trigger: true
  - aggregate:
    - task: build
      config:
        platform: linux
        rootfs_uri: docker:///cloudfoundry/cli-ci
        inputs:
        - name: diego-enabler
          path: gopath/src/github.com/cloudfoundry-incubator/diego-enabler
        outputs:
        - name: diego-enabler-releases

        run:
          path: bash
          args:
          - -c
          - |
            set -ex

            cwd=$PWD

            export GOPATH=$PWD/gopath
            export PATH=$GOPATH/bin:$PATH

            go get github.com/mitchellh/gox

            pushd $GOPATH/src/github.com/cloudfoundry-incubator/diego-enabler
              ./bin/build
            popd

            cp $GOPATH/src/github.com/cloudfoundry-incubator/diego-enabler/out/* diego-enabler-releases

    - task: units
      config:
        platform: linux
        rootfs_uri: docker:///cloudfoundry/cli-ci
        inputs:
        - name: diego-enabler
          path: gopath/src/github.com/cloudfoundry-incubator/diego-enabler

        run:
          path: bash
          args:
          - -c
          - |
            set -ex

            cwd=$PWD

            export GOPATH=$PWD/gopath
            export PATH=$GOPATH/bin:$PATH

            go get github.com/onsi/ginkgo/ginkgo
            go get github.com/mitchellh/gox

            pushd $GOPATH/src/github.com/cloudfoundry-incubator/diego-enabler
              ./bin/test
            popd
  - aggregate:
    - put: diego-enabler-draft-release
      params:
          name: diego-enabler/ci/draft-release-name
          tag: diego-enabler/ci/draft-release-tag
          globs:
          - diego-enabler-releases/diego-enabler_darwin_amd64
          - diego-enabler-releases/diego-enabler_linux_386
          - diego-enabler-releases/diego-enabler_linux_amd64
          - diego-enabler-releases/diego-enabler_windows_386.exe
          - diego-enabler-releases/diego-enabler_windows_amd64.exe
