// This file was generated by counterfeiter
package migratehelpersfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/diego-enabler/commands/migratehelpers"
)

type FakeDiegoFlagSetter struct {
	SetDiegoFlagStub        func(string, bool) ([]string, error)
	setDiegoFlagMutex       sync.RWMutex
	setDiegoFlagArgsForCall []struct {
		arg1 string
		arg2 bool
	}
	setDiegoFlagReturns struct {
		result1 []string
		result2 error
	}
	HasRoutesStub        func(appName string) (bool, error)
	hasRoutesMutex       sync.RWMutex
	hasRoutesArgsForCall []struct {
		appName string
	}
	hasRoutesReturns struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDiegoFlagSetter) SetDiegoFlag(arg1 string, arg2 bool) ([]string, error) {
	fake.setDiegoFlagMutex.Lock()
	fake.setDiegoFlagArgsForCall = append(fake.setDiegoFlagArgsForCall, struct {
		arg1 string
		arg2 bool
	}{arg1, arg2})
	fake.recordInvocation("SetDiegoFlag", []interface{}{arg1, arg2})
	fake.setDiegoFlagMutex.Unlock()
	if fake.SetDiegoFlagStub != nil {
		return fake.SetDiegoFlagStub(arg1, arg2)
	} else {
		return fake.setDiegoFlagReturns.result1, fake.setDiegoFlagReturns.result2
	}
}

func (fake *FakeDiegoFlagSetter) SetDiegoFlagCallCount() int {
	fake.setDiegoFlagMutex.RLock()
	defer fake.setDiegoFlagMutex.RUnlock()
	return len(fake.setDiegoFlagArgsForCall)
}

func (fake *FakeDiegoFlagSetter) SetDiegoFlagArgsForCall(i int) (string, bool) {
	fake.setDiegoFlagMutex.RLock()
	defer fake.setDiegoFlagMutex.RUnlock()
	return fake.setDiegoFlagArgsForCall[i].arg1, fake.setDiegoFlagArgsForCall[i].arg2
}

func (fake *FakeDiegoFlagSetter) SetDiegoFlagReturns(result1 []string, result2 error) {
	fake.SetDiegoFlagStub = nil
	fake.setDiegoFlagReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeDiegoFlagSetter) HasRoutes(appName string) (bool, error) {
	fake.hasRoutesMutex.Lock()
	fake.hasRoutesArgsForCall = append(fake.hasRoutesArgsForCall, struct {
		appName string
	}{appName})
	fake.recordInvocation("HasRoutes", []interface{}{appName})
	fake.hasRoutesMutex.Unlock()
	if fake.HasRoutesStub != nil {
		return fake.HasRoutesStub(appName)
	} else {
		return fake.hasRoutesReturns.result1, fake.hasRoutesReturns.result2
	}
}

func (fake *FakeDiegoFlagSetter) HasRoutesCallCount() int {
	fake.hasRoutesMutex.RLock()
	defer fake.hasRoutesMutex.RUnlock()
	return len(fake.hasRoutesArgsForCall)
}

func (fake *FakeDiegoFlagSetter) HasRoutesArgsForCall(i int) string {
	fake.hasRoutesMutex.RLock()
	defer fake.hasRoutesMutex.RUnlock()
	return fake.hasRoutesArgsForCall[i].appName
}

func (fake *FakeDiegoFlagSetter) HasRoutesReturns(result1 bool, result2 error) {
	fake.HasRoutesStub = nil
	fake.hasRoutesReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeDiegoFlagSetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.setDiegoFlagMutex.RLock()
	defer fake.setDiegoFlagMutex.RUnlock()
	fake.hasRoutesMutex.RLock()
	defer fake.hasRoutesMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDiegoFlagSetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migratehelpers.DiegoFlagSetter = new(FakeDiegoFlagSetter)
